#!/bin/sh
# Ensure alphanumeric sort output is correct

# Copyright (C) 2009-2010 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes; then
  set -x
  ls --version
fi

. $srcdir/test-lib.sh

touch foo1x.txt || framework_failure
touch foo12x.txt || framework_failure
touch foo2x.txt  || framework_failure
touch foo20x.txt  || framework_failure

ls -Y -1 > out || fail=1

cat <<\EOL > exp || framework_failure
foo1x.txt
foo2x.txt
foo12x.txt
foo20x.txt
EOL

cmp out exp || fail=1

Exit $fail